/** @format */

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "700", "800"],
});

export const metadata: Metadata = {
    title: "One million checkboxes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${poppins.className} min-h-screen  w-full`}>
                <div className='bg-gray-900 max-w-xl mx-auto min-h-screen'>
                    {children}
                </div>
            </body>
        </html>
    );
}
